application: appscale-filehosting
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /
  script: filehosting.app

- url: /apps/(.+)
  script: filehosting.app

- url: /download/(.+)
  script: filehosting.app

- url: /edit/(.+)
  script: filehosting.app
  login: admin

- url: /upload
  script: filehosting.app
  login: admin

- url: /upload-successful
  script: filehosting.app
  login: admin

- url: /upload-internal
  script: filehosting.app
  login: admin

libraries:
- name: jinja2
  version: 2.6
